# Generated by Django 3.1.3 on 2020-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_image', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
