# Generated by Django 3.1.3 on 2020-11-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20201119_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
