# Generated by Django 3.1.3 on 2020-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20201119_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FilePathField(default='/media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
