# Generated by Django 3.1.3 on 2020-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20201119_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image_path',
            field=models.URLField(),
        ),
    ]
