# Generated by Django 3.1.3 on 2020-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20201119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='saved_image',
            field=models.URLField(),
        ),
    ]
